name: Continuous Integration Workflow

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.path .virtualenvs

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
          cache-dependency-path: poetry.lock
      
      - name: Set poetry environment
        run: poetry env use ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Lint
        run: poetry run ruff check unsupervised_bias_detection
      
      - name: Test
        run: poetry run pytest
          --color=yes
          --full-trace
          --showlocals
          --verbose
